# SAW - Pemilihan HP

Kriteria:
1. Harga (Juta Rp) -> Cost (Makin murah makin bagus)
2. RAM (GB) -> Benefit (Makin besar makin bagus)
3. Kamera (MP) -> Benefit (Makin besar makin bagus)
4. Baterai (mAh) -> Benefit (Makin besar makin bagus)

Alternatif:
1. Samsung (A1): Rp 4 Juta, RAM 8GB, Kamera 50MP, Baterai 5000mAh
2. Xiaomi (A2): Rp 3 Juta, RAM 12GB, Kamera 108MP, Baterai 4500mAh
3. iPhone (A3): Rp 10 Juta, RAM 6GB, Kamera 12MP, Baterai 3500mAh

## Menggunakan Data Manual

In [1]:
import numpy as np
import pandas as pd

Alternatif

In [2]:
alternatif = ['Samsung', 'Xiaomi', 'iPhone']
kriteria = ['Harga', 'RAM', 'Kamera', 'Baterai']

# Matriks Keputusan (X)
# Baris = Alternatif, Kolom = Kriteria (Harga, RAM, Kamera, Baterai)
data = np.array([
    [4,  8,  50, 5000],  # A1
    [3, 12, 108, 4500],  # A2
    [10, 6,  12, 3500]   # A3
])

# Bobot Preferensi (W) - Total harus 1.0 (atau 100%)
# Urutan: [Harga, RAM, Kamera, Baterai]
bobot = np.array([0.30, 0.20, 0.20, 0.30])

# Menentukan Nilai Atribut masing-masing Kriteria
# 0 = Cost, 1 = Benefit
atribut = np.array([0, 1, 1, 1])

df = pd.DataFrame(data, index=alternatif, columns=kriteria)
print('Matriks Keputusan :')
print(df)

print('\nBobot yang diberikan')
print('Bobot = ', bobot)
print('\nAtribut tiap kriteria')
print('Atribut = ', atribut)

Matriks Keputusan :
         Harga  RAM  Kamera  Baterai
Samsung      4    8      50     5000
Xiaomi       3   12     108     4500
iPhone      10    6      12     3500

Bobot yang diberikan
Bobot =  [0.3 0.2 0.2 0.3]

Atribut tiap kriteria
Atribut =  [0 1 1 1]


TAHAP 1: Normalisasi

In [3]:
m, n = data.shape
normalized_matrix = np.zeros((m,n))

# Normalisasi
for j in range(n):
  if atribut[j] == 1: # Kriteria Benefit
    normalized_matrix[:, j] = data[:,j] / np.max(data[:,j])
  else: # Kriteria Cost
    normalized_matrix[:, j] = np.min(data[:,j]) / data[:,j]
    
normalized_df = pd.DataFrame(normalized_matrix, index=alternatif, columns=kriteria)
print('Matriks Ternormalisasi :')
print(normalized_df)

Matriks Ternormalisasi :
         Harga       RAM    Kamera  Baterai
Samsung   0.75  0.666667  0.462963      1.0
Xiaomi    1.00  1.000000  1.000000      0.9
iPhone    0.30  0.500000  0.111111      0.7


TAHAP 2: Menghitung Nilai Preferensi

In [4]:
value_preferensi = np.dot(normalized_matrix, bobot) # Ngedot / Perkalian matriks

# Hasil
ranking = pd.DataFrame(value_preferensi, index=alternatif, columns=['Nilai Preferensi'])
sort_ranking = ranking.sort_values(by='Nilai Preferensi', ascending=False)
print('\nHasil Ranking :')
print(sort_ranking)

best_alternatif = sort_ranking.index[0]
print(f'\nAlternatif Terbaik adalah : {best_alternatif}')


Hasil Ranking :
         Nilai Preferensi
Xiaomi           0.970000
Samsung          0.750926
iPhone           0.422222

Alternatif Terbaik adalah : Xiaomi


## Menggunakan Dataset CSV

In [5]:
import numpy as np
import pandas as pd

In [6]:
df = pd.read_csv('smartphone.csv')

print("=== Data Awal ===")
print(df)

=== Data Awal ===
  Alternatif  Harga  RAM  Kamera  Baterai
0    Samsung      4    8      50     5000
1     Xiaomi      3   12     108     4500
2     iPhone     10    6      12     3500


In [7]:
alternatif = df.iloc[:, 0].tolist()  # Mengambil kolom alternatif
kriteria = df.columns[1:].tolist() # Mengambil kolom kriteria

data = df.iloc[:, 1:].values     # Mengambil semua kolom angka

# Bobot Preferensi (W) - Total harus 1.0 (atau 100%)
# Urutan: [Harga, RAM, Kamera, Baterai]
bobot = np.array([0.30, 0.20, 0.20, 0.30])

# Menentukan Nilai Atribut masing-masing Kriteria
# 0 = Cost, 1 = Benefit
atribut = np.array([0, 1, 1, 1])

print('alternatif:\n', alternatif)
print('kriteria:\n', kriteria)
print('data:\n', data)

alternatif:
 ['Samsung', 'Xiaomi', 'iPhone']
kriteria:
 ['Harga', 'RAM', 'Kamera', 'Baterai']
data:
 [[   4    8   50 5000]
 [   3   12  108 4500]
 [  10    6   12 3500]]


TAHAP 1: Normalisasi

In [8]:
m, n = data.shape
normalized_matrix = np.zeros((m,n))

# Normalisasi
for j in range(n):
  if atribut[j] == 1: # Data Benefit
    normalized_matrix[:, j] = data[:,j] / np.max(data[:,j])
  else: # Data Cost
    normalized_matrix[:, j] = np.min(data[:,j]) / data[:,j]
    
normalized_df = pd.DataFrame(normalized_matrix, index=alternatif, columns=kriteria)
print('Matriks Ternormalisasi :')
print(normalized_df)

Matriks Ternormalisasi :
         Harga       RAM    Kamera  Baterai
Samsung   0.75  0.666667  0.462963      1.0
Xiaomi    1.00  1.000000  1.000000      0.9
iPhone    0.30  0.500000  0.111111      0.7


TAHAP 2: Menghitung Nilai Preferensi

In [9]:
value_preferensi = np.dot(normalized_matrix, bobot) # Ngedot / Perkalian matriks

# Hasil
ranking = pd.DataFrame(value_preferensi, index=alternatif, columns=['Nilai Preferensi'])
sort_ranking = ranking.sort_values(by='Nilai Preferensi', ascending=False)
print('\nHasil Ranking :')
print(sort_ranking)

best_alternatif = sort_ranking.index[0]
print(f'\nAlternatif Terbaik adalah : {best_alternatif}')


Hasil Ranking :
         Nilai Preferensi
Xiaomi           0.970000
Samsung          0.750926
iPhone           0.422222

Alternatif Terbaik adalah : Xiaomi
