# Pertemuan 2: Matriks

## 1. Deklarasi Matriks

### Deklarasi sekaligus inisialisasi nilai matriks

In [45]:
matriks = [[1,2,3],[4,5,6]]
print(matriks)

[[1, 2, 3], [4, 5, 6]]


### Deklarasi dengan nilai default

In [46]:
matriks = [[0 for j in range(4)] for i in range(3)]
print(matriks)

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]


### Deklarasi dengan library NumPy

In [47]:
import numpy as np

In [48]:
matriks = np.array([[1,2,3],[4,5,6]])
print(matriks)

[[1 2 3]
 [4 5 6]]


In [49]:
# Skalar
scalar = np.array(5)
print("Skalar:", scalar)

# Vektor baris (1×n)
row_vector = np.array([1, 2, 3])
print("Vektor Baris:", row_vector)

# Vektor kolom (n×1)
column_vector = np.array([[1], [2], [3]])
print("Vektor Kolom:\n", column_vector)

Skalar: 5
Vektor Baris: [1 2 3]
Vektor Kolom:
 [[1]
 [2]
 [3]]


In [50]:
# Matriks 2D
matriks_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("Matriks 2D:\n", matriks_2d)

# Matriks 3x3
matriks_3x3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matriks 3x3:\n", matriks_3x3)

Matriks 2D:
 [[1 2 3]
 [4 5 6]]
Matriks 3x3:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [51]:
zeros_matrix = np.zeros((3, 3))
print("Matriks Nol (3x3):\n", zeros_matrix)

ones_matrix = np.ones((2, 4))
print("Matriks Elemen Satu (2x4):\n", ones_matrix)

identity_matrix = np.eye(4)
print("Matriks Identitas (4x4):\n", identity_matrix)

random_matrix = np.random.rand(3, 3)
print("Matriks Acak (3x3):\n", random_matrix)

random_int_matrix = np.random.randint(1,11, size=(3, 3))
print("Matriks Acak Bilangan Bulat (3x3):\n", random_int_matrix)

Matriks Nol (3x3):
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Matriks Elemen Satu (2x4):
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Matriks Identitas (4x4):
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Matriks Acak (3x3):
 [[0.7751882  0.47243302 0.45972857]
 [0.77438892 0.78938717 0.91870682]
 [0.13117362 0.69641646 0.75315397]]
Matriks Acak Bilangan Bulat (3x3):
 [[ 1  7 10]
 [ 3  4  5]
 [ 9  8  5]]


## 2. Akses Elemen Matriks

In [52]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Mengakses elemen tertentu
print("Elemen baris ke-1, kolom ke-2:", A[0, 1])

# Mengakses seluruh elemen di baris tertentu
print("Baris ke-2:", A[1, :])

# Mengakses seluruh elemen di kolom tertentu
print("Kolom ke-3:", A[:, 2])

# Mengakses sub-matriks (bagian matriks)
print("Sub-matriks:\n", A[0:2, 1:3])

Elemen baris ke-1, kolom ke-2: 2
Baris ke-2: [4 5 6]
Kolom ke-3: [3 6 9]
Sub-matriks:
 [[2 3]
 [5 6]]


## 3. Operasi Matriks

Operasi matriks lebih efisien dilakukan menggunakan library NumPy

### Operasi Elemen

In [53]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Perkalian elemen-per-elemen
C = A * B
print("Perkalian Elemen-per-Elemen:\n", C)

# Perkalian elemen dengan konstanta
C = A * 2
print("Perkalian Elemen dengan Konstanta:\n", C)

# Pembagian elemen-per-elemen
D = A / B
print("Pembagian Elemen-per-Elemen:\n", D)

# Penjumlahan dan Pengurangan elemen
E = A + B
F = A - B
print("Penjumlahan Elemen:\n", E)
print("Pengurangan Elemen:\n", F)

# Pangkat elemen-per-elemen
G = A ** 2
print("Pangkat Elemen:\n", G)

Perkalian Elemen-per-Elemen:
 [[ 5 12]
 [21 32]]
Perkalian Elemen dengan Konstanta:
 [[2 4]
 [6 8]]
Pembagian Elemen-per-Elemen:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
Penjumlahan Elemen:
 [[ 6  8]
 [10 12]]
Pengurangan Elemen:
 [[-4 -4]
 [-4 -4]]
Pangkat Elemen:
 [[ 1  4]
 [ 9 16]]


### Operasi Aljabar Matriks

In [54]:
A = np.array(
    [[1, 2],
    [3, 4]]
)
B = np.array(
    [[5, 6],
    [7, 8]]
)

# Perkalian Matriks
C = np.dot(A, B)
print("Perkalian Matriks:\n", C)

# Invers Matriks
inv_A = np.linalg.inv(A)
print("Invers Matriks:\n", inv_A)

# Transpose Matriks
A_T = A.T
print("Transpose Matriks:\n", A_T)

Perkalian Matriks:
 [[19 22]
 [43 50]]
Invers Matriks:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Transpose Matriks:
 [[1 3]
 [2 4]]


In [55]:
# Determinan Matriks
det_A = np.linalg.det(A)
print("Determinan Matriks:\n", det_A)

# Eigenvalues & Eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Nilai Eigen:\n", eigenvalues)
print("Vektor Eigen:\n", eigenvectors)

# Rank Matriks
rank_A = np.linalg.matrix_rank(A)
print("Rank Matriks:\n", rank_A)

Determinan Matriks:
 -2.0000000000000004
Nilai Eigen:
 [-0.37228132  5.37228132]
Vektor Eigen:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
Rank Matriks:
 2


### Persamaan Linear dalam Matriks

Persamaan linear:
$$
\begin{aligned}
x - 2y &= 32 \\
12x + 5y &= 7
\end{aligned}
$$

Matriks:
$$
\underbrace{
\begin{bmatrix}
1 & -2 \\
12 & 5
\end{bmatrix}
}_{A}
\underbrace{
\begin{bmatrix}
x \\
y
\end{bmatrix}
}_{X}
= \underbrace{
\begin{bmatrix}
32 \\
7
\end{bmatrix}
}_{B}
$$

Untuk mencari nilai $x$ dan $y$ (yaitu Matriks $X$), kita tidak bisa membagi $B$ dengan $A$. Kita harus mengalikan invers dari matriks $A$ dengan matriks $B$:

$$
X = A^{-1}B
$$

In [56]:
# Matriks koefisien
A = np.array([[1, -2], [12, 5]])

# Vektor konstanta
B = np.array([32, 7])

# Menghitung invers matriks
A_inv = np.linalg.inv(A)

# Menghitung solusi
X = np.dot(A_inv, B)
print("Solusi:\n", X)

Solusi:
 [  6. -13.]


Sehingga kita dapatkan solusi x = 6 dan y = -13. Atau dapat diselesaikan dengan
menggunakan operator pembagian terbalik:

In [57]:
# Menggunakan pembagian balik
X = np.linalg.solve(A, B)
print("Solusi dengan np.linalg.solve:\n", X)

Solusi dengan np.linalg.solve:
 [  6. -13.]


## 4. Penggabungan Matriks

### Penggabungan Horizontal

In [58]:
# Definisi matriks
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Penggabungan horizontal
H = np.hstack((A, B))
print("Hasil Penggabungan Horizontal:\n", H)

Hasil Penggabungan Horizontal:
 [[1 2 5 6]
 [3 4 7 8]]


### Penggabungan Horizontal

In [59]:
# Definisi matriks
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Penggabungan vertikal
V = np.vstack((A, B))
print("Hasil Penggabungan Vertikal:\n", V)

Hasil Penggabungan Vertikal:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


### Menggabungkan Lebih dari Dua Matriks

In [60]:
# Definisi matriks
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.array([[9, 10], [11, 12]])

# Penggabungan horizontal tiga matriks
H_multi = np.hstack((A, B, C))
print("Gabungan Horizontal Tiga Matriks:\n", H_multi)

# Penggabungan vertikal tiga matriks
V_multi = np.vstack((A, B, C))
print("Gabungan Vertikal Tiga Matriks:\n", V_multi)

Gabungan Horizontal Tiga Matriks:
 [[ 1  2  5  6  9 10]
 [ 3  4  7  8 11 12]]
Gabungan Vertikal Tiga Matriks:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


## 5. Pembentukan Ulang Matriks

### Mengubah Dimensi Matriks

1. **`reshape()`**
- Mengubah dimensi matriks, **SYARATNYA:** total elemen matriks harus sama persis.
- Misal: Matriks 2x3 (total 6 elemen) bisa diubah jadi 3x2 atau 1x6. Kalau dipaksa jadi 3x3 (butuh 9 elemen), program akan **Error**.

In [61]:
# Matriks awal
A = np.array([1, 2, 3, 4, 5, 6])

# Mengubah bentuk menjadi matriks 2x3
reshaped_A = A.reshape(2, 3)
print("Matriks Reshape 2x3:\n", reshaped_A)

# Mengubah bentuk menjadi matriks 3x2
reshaped_A2 = A.reshape(3, 2)
print("Matriks Reshape 3x2:\n", reshaped_A2)

Matriks Reshape 2x3:
 [[1 2 3]
 [4 5 6]]
Matriks Reshape 3x2:
 [[1 2]
 [3 4]
 [5 6]]


2. **`resize()`**
- Mengubah dimensi matriks tanpa peduli jumlah elemen awal.
- Kalau elemennya **kurang**, dia akan mengulang data dari awal (*copy-paste*).
- Kalau elemennya **sisa**, datanya akan dibuang/dipotong.

In [62]:
# Matriks awal
C = np.array([1, 2, 3, 4])

# Mengubah ukuran menjadi 3x3
resized_C = np.resize(C, (3, 3))
print("Matriks Resize 3x3:\n", resized_C)

Matriks Resize 3x3:
 [[1 2 3]
 [4 1 2]
 [3 4 1]]


### Meratakan Dimensi Matriks

Fungsi np.flatten digunakan meratakan dimensi matriks menjadi satu dimensi.

In [63]:
# Matriks awal
B = np.array([[1, 2, 3], [4, 5, 6]])

flattened_B = B.flatten()
print("Matriks Diratakan (flatten):", flattened_B)

Matriks Diratakan (flatten): [1 2 3 4 5 6]
