# AHP - Pemilihan Motor

Penentuan **Alternatif** dan **Kriteria**
- Alternatif:
  - A1: Yamaha
  - A2: Honda
  - A3: Suzuki
  - A4: Kawasaki
- Kriteria:
  - C1: Gaya
  - C2: Keandalan
  - C3: Keekonomisan Bahan Bakar

**Tingkat Kepentingan**:
| Intensitas | Keterangan |
|------------|------------|
| 1 | X dan Y sama penting/baik |
| 2 | X sedikit lebih penting/baik dari Y |
| 3 | X lebih penting/baik dari Y |
| 4 | X jauh lebih penting/baik dari Y |

**Preferensi Kriteria**
1. *Keandalan* dua kali lebih penting dari gaya.
2. *Gaya* tiga kali lebih penting dari keekonomisan bahan bakar.
3. *Keandalan* empat kali lebih penting dari keekonomisan bahan bakar.

**Preferensi Alternatif**
1. Preferensi Gaya:
   - Kawasaki > Honda > Yamaha > Suzuki
2. Preferensi Keandalan:
   - Honda > Yamaha > Kawasaki > Suzuki 
3. Nilai Keekonomisan Bahan Bakar:
   - Yamaha  : 60
   - Honda   : 80
   - Suzuki  : 60
   - Kawasaki: 80

In [10]:
import numpy as np

In [11]:
def normalize_comparation(M):
    """Fungsi untuk normalisasi matriks perbandingan berpasangan"""
    # menjumlahkan elemen-elemen dalam kolom yang sama
    sumCol = M.sum(axis=0) # axis 0 = kolom, 1 = baris
    norm = M / sumCol
    return norm

def weight(M):
    """Fungsi untuk menghitung bobot"""
    # menghitung rata-rata baris
    return np.mean(M, axis=1)

def validity_check(M, W):
    """Fungsi untuk mengecek validitas bobot"""
    n = len(M)
    RI = {
        2: 0.00, 3: 0.58, 4: 0.90, 5: 1.12, 6: 1.24, 7: 1.32, 8: 1.41, 9: 1.45,
        10: 1.51, 11: 1.53, 12: 1.54, 13: 1.56, 14: 1.57
    }
    
    # menghitung CV
    CV = M @ W / W # operator @ mengalikan matriks sesuai dengan prinsipnya
    print(f"CV: {CV}\n")
    
    # menghitung nilai eigen
    eigen = np.mean(CV)
    print(f"Eigen: {eigen}\n")
    
    # mencari nilai RI
    print(f"RI: {RI[n]}\n")
    
    # menghitung CI
    CI = (eigen - n) / (n - 1)
    print(f"CI: {CI}\n")
    
    # menghitung CR
    CR = CI / RI[n]
    print(f"CR: {CR}\n")
    
    if CR <= 0.1:
        print("Bobot valid!\n")
    else:
        print("Bobot tidak valid!\n")

def final_weight(W_alt, W_crit):
    """Menghitung bobot akhir tiap alternatif"""
    # mengalikan bobot alternatif dan kriteria sesuai dengan prinsip matriks
    W_fin = W_alt.T @ W_crit
    return W_fin

## 1. Evaluasi Bobot Kriteria

Matriks Perbandingan Berpasangan Kriteria

In [12]:
# alternatif
A = ["Yamaha", "Honda", "Suzuki", "Kawasaki"]

print("=== Kriteria ===")
# matriks perbandingan berpasangan kriteria
# urutan: gaya, keandalan, keekonomisan
MPBk = np.array([
    [1, 1/2, 3],
    [2, 1, 4],
    [1/3, 1/4, 1]
])
print(f"Matriks perbandingan:\n{MPBk}")

=== Kriteria ===
Matriks perbandingan:
[[1.         0.5        3.        ]
 [2.         1.         4.        ]
 [0.33333333 0.25       1.        ]]


Normalisasi & Perhitungan Bobot

In [13]:
# normalisasi
MPBk_norm = normalize_comparation(MPBk)
print(f"Matriks perbandingan setelah normalisasi:\n{MPBk_norm}")

# perhitungan bobot
Wk = weight(MPBk_norm)
print(f"\nBobot kriteria:\n{Wk}")

Matriks perbandingan setelah normalisasi:
[[0.3        0.28571429 0.375     ]
 [0.6        0.57142857 0.5       ]
 [0.1        0.14285714 0.125     ]]

Bobot kriteria:
[0.3202381  0.55714286 0.12261905]


Uji Validitas Bobot

In [14]:
# uji validitas bobot
validity_check(MPBk, Wk)

CV: [3.01858736 3.02991453 3.00647249]

Eigen: 3.01832479413957

RI: 0.58

CI: 0.009162397069784944

CR: 0.015797236327215424

Bobot valid!



## 2. Evaluasi Alternatif Tiap Kriteria

### Kriteria Gaya

In [15]:
print("=== Kriteria: Gaya ===")
# urutan: yamaha, honda, suzuki, kawasaki
MPBg = np.array([
    [1, 1/2, 2, 1/3],
    [2, 1, 3, 1/2],
    [1/2, 1/3, 1, 1/4],
    [3, 2, 4, 1]
])
MPBg_norm = normalize_comparation(MPBg)
Wg = weight(MPBg_norm)
print(f"Bobot Gaya (Wg): {Wg}\n")
validity_check(MPBg, Wg)

=== Kriteria: Gaya ===
Bobot Gaya (Wg): [0.16107023 0.27714047 0.0959699  0.4658194 ]

CV: [4.01597107 4.04163398 4.01521752 4.05133544]

Eigen: 4.03103950215422

RI: 0.9

CI: 0.010346500718073415

CR: 0.011496111908970461

Bobot valid!



### Kriteria Keandalan

In [16]:
print("=== Kriteria: Keandalan ===")
MPBa = np.array([
    [1, 1/2, 3, 2],
    [2, 1, 4, 3],
    [1/3, 1/4, 1, 1/2],
    [1/2, 1/3, 2, 1]
])
MPBa_norm = normalize_comparation(MPBa)
Wa = weight(MPBa_norm)
print(f"Bobot Keandalan (Wa): {Wa}\n")
validity_check(MPBa, Wa)

=== Kriteria: Keandalan ===
Bobot Keandalan (Wa): [0.27714047 0.4658194  0.0959699  0.16107023]

CV: [4.04163398 4.05133544 4.01521752 4.01597107]

Eigen: 4.03103950215422

RI: 0.9

CI: 0.010346500718073415

CR: 0.011496111908970461

Bobot valid!



### Kriteria Keekonomisan

In [17]:
print("=== Kriteria: Keekonomisan ===")
MPBe = np.array([
    [1, 60/80, 1, 60/80],
    [80/60, 1, 80/60, 1],
    [1, 60/80, 1, 60/80],
    [80/60, 1, 80/60, 1]
])
MPBe_norm = normalize_comparation(MPBe)
We = weight(MPBe_norm)
print(f"Bobot Keekonomisan (We): {We}\n")
validity_check(MPBe, We)

=== Kriteria: Keekonomisan ===
Bobot Keekonomisan (We): [0.21428571 0.28571429 0.21428571 0.28571429]

CV: [4. 4. 4. 4.]

Eigen: 4.0

RI: 0.9

CI: 0.0

CR: 0.0

Bobot valid!



## 3. Perankingan Akhir

In [18]:
# menyatukan semua bobot alternatif dalam satu matriks (Rekap Bobot)
W_total = np.array([Wg, Wa, We])
print(f"Matriks Rekap Bobot Alternatif (W_total):\n{W_total}\n")

# menghitung bobot akhir
W_final = final_weight(W_total, Wk)
print(f"Bobot akhir tiap alternatif:\n{W_final}\n")

# memunculkan alternatif terbaik
max_index = np.argmax(W_final)
print(f"Alternatif terbaik adalah {A[max_index]} dengan nilai {W_final[max_index]:.4f}")

Matriks Rekap Bobot Alternatif (W_total):
[[0.16107023 0.27714047 0.0959699  0.4658194 ]
 [0.27714047 0.4658194  0.0959699  0.16107023]
 [0.21428571 0.28571429 0.21428571 0.28571429]]

Bobot akhir tiap alternatif:
[0.23226317 0.3833129  0.11047767 0.27394626]

Alternatif terbaik adalah Honda dengan nilai 0.3833
